### ISSUE TITLE
How to use MuleSoft's visual API Designer to create a To-Do API specification using clicks, not code

### ISSUE THREAD

**Issue by alexandramartinez** [ProstDev/blog-posts#3]
- [x] Draft post created in ProstDev
- [x] Cover image
- [x] Schedule/post in LinkedIn
- [x] Send to ProstDev Slack
- [x] Send to MC Slack 
- [x] Post in LI groups
- [x] Post in Facebook group

---

```
#NewPOST ~ How to use MuleSoft's visual API Designer to create a To-Do API specification using clicks, not code by Alex Martinez

Did you know MuleSoft provides this neat Graphical User Interface (GUI) where you can configure your own API specification with just clicks? That's right, you don't have to learn RAML or OAS anymore. You can just follow this visual tool to create them and it gives you the code you need in whichever format you need it!

Let's create a To-Do API specification to see how this tool works.

https://www.prostdev.com/post/how-to-use-mulesoft-s-visual-api-designer-to-create-a-to-do-api-specification-using-clicks-not-code
```
